name: Generate documentation

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to grab docs from'
        required: true
        type: string
        default: 'release/midnight'
      docs_branch:
        description: 'Branch to merge with in midnight-docs'
        required: true
        type: string
        default: 'main'
      pr_description:
        description: 'PR description for docs'
        required: true
        type: string
        default: 'Example PR description for midnight-docs'
      draft_pr:
        description: 'Create PR as draft'
        required: false
        type: boolean
        default: false
    secrets:
      MIDNIGHTCI_PACKAGES_READ:
        required: true
      MIDNIGHTCI_PACKAGES_WRITE:
        required: true
      ATTIC_CACHE_TOKEN:
        required: true
      MIDNIGHTCI_REPO:
        required: true

jobs:
  generate-docs:
    runs-on: ubuntu-latest-16-core-x64
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@8663542d03a41382d97ee344a4e3955280db5f95 # latest
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Checkout compactc repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup .npmrc
        run: |
          cd ./runtime
          echo "
          //npm.pkg.github.com/:_authToken=${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
          @midnight-ntwrk:registry=https://npm.pkg.github.com/
          " > .npmrc

      - name: Configure yarn
        run: |
          cd ./runtime
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}"
          echo 'checksumBehavior: update' >> ./.yarnrc.yml

      - name: Build runtime
        run: |
          nix build .#runtime.forPublish

      - name: Generate runtime docs
        run: |
          nix develop --command bash -c "cd ./runtime ; npm run build ; npm run generate-docs"

      - name: Checkout docs repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "midnightntwrk/midnight-docs"
          token: ${{ secrets.MIDNIGHTCI_REPO }}
          path: "midnight-docs"
          ref: ${{ inputs.docs_branch }}

      - name: Manual Git Push
        run: |
          cd midnight-docs
          git config user.name "midnight-ci"
          git config user.email "ci@midnight.network"

          git checkout -b compact-docs-update-${{ github.run_id }}

          cp ../doc/ledger-adt.mdx docs/compact/data-types
          cp ../doc/lang-ref.mdx docs/compact/reference
          cp ../doc/api/CompactStandardLibrary/exports.md docs/compact/standard-library
          cp ../doc/api/CompactStandardLibrary/README.md docs/compact/standard-library
          cp ../doc/compiler-usage.md docs/compact/compilation-and-tooling/compiler-usage.mdx
          cp -r ../doc/api/runtime/. ./api-reference/compact-runtime
          echo -e "# Compact runtime API\n\n$(cat ../doc/api/runtime/README.md)" > ./api-reference/compact-runtime/README.md
          cp -r ../doc/Compact.html ./static/language/compact.html
          cp -r ../doc/ledger-adt.mdx ./static/language/ledger-adt.mdx
          # cp -r ../doc/all-keywords.html ./static/language/all-keywords.html

          git add .
          git commit -m "Update compact documentation"
          git push origin compact-docs-update-${{ github.run_id }}

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.MIDNIGHTCI_REPO }}
        run: |
          DRAFT_FLAG=""
          if [ "${{ inputs.draft_pr }}" = "true" ]; then
            DRAFT_FLAG="--draft"
          fi
          gh pr create \
            --repo midnightntwrk/midnight-docs \
            --base ${{ inputs.docs_branch }} \
            --head "compact-docs-update-${{ github.run_id }}" \
            --title "${{ inputs.pr_description }}" \
            --body 'PR: ${{ inputs.pr_description }}' \
            $DRAFT_FLAG
